export { Body, type BodyProps } from './Body'
export { Caption, type CaptionProps } from './Caption'
export { Title, type TitleProps } from './Title'
export { Subtitle, type SubtitleProps } from './Subtitle'
export { Service, type ServiceProps } from './Service'
export { Anchor, type AnchorProps } from './Anchor'
